use_frameworks!

platform :ios, '8.0'

target 'TRUNetworking_Example' do
  pod 'TRUNetworking', :path => '../'
  pod 'smallDoubleBlack', '~> 0.0.1'

  target 'TRUNetworking_Tests' do
    inherit! :search_paths

  end
end
